version: 1.2.3.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    cd src

    cd .paket

    paket.bootstrapper.exe

    cd ..

    .paket\paket.exe install

    cd ..
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd src

    .paket\paket.exe pack output nupkgs

    cd ..
artifacts:
- path: src\nupkgs
  name: nupkgs